version: "3.7"
services:
  webapp:
    image: portal-video
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    tty: true

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
